name: Runs Maven Install
on:
    workflow_call:

        inputs:
            ref_name:
                required: true
                type: string
                description: tag or branch name
            app_name:
                required: true
                type: string
            app_directory:
                required: true
                type: string
            java_version:
                default: '17'
                type: string
                required: false
            jib_container_volumes:
                default: '/config/'
                type: string
                required: false
                description: comma-separated container volumes for jib-maven-plugin (default /config/)

        secrets:
            artifactory_user:
                required: true
            artifactory_password:
                required: true
            artifactory_url:
                required: true
            artifactory_repo:
                required: true
            acr_registry:
                required: true
            acr_username:
                required: true
            acr_password:
                required: true

jobs:
    create-docker-image:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v2
                with:
                    ref: ${{ inputs.ref_name }}
            -   name: Git Status
                run: git status
            -   name: Set up JDK
                uses: actions/setup-java@v2
                with:
                    java-version: ${{ inputs.java_version }}
                    distribution: 'adopt'
            -   name: Cache Maven packages
                uses: actions/cache@v2
                with:
                    path: ~/.m2/repository
                    key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
                    restore-keys: ${{ runner.os }}-m2
            -   name: Create settings.xml
                uses: whelk-io/maven-settings-xml-action@v4
                with:
                    servers: '[{"id": "ubique-artifactory", "username": "${{ secrets.artifactory_user}}", "password": "${{ secrets.artifactory_password }}"}]'
                    repositories: '[{"id" : "ubique-artifactory", "url" : "${{ secrets.artifactory_url }}${{ secrets.artifactory_repo }}"}]'
            -   name: Get version
                env:
                    REF_NAME: ${{ inputs.ref_name }}
                run: echo "VERSION=${REF_NAME/[v\/]/}" >> $GITHUB_ENV
            -   name: Set versions
                run: mvn -f ${{ inputs.app_directory }}/../pom.xml versions:set -DnewVersion=$VERSION
            -   name: Commit versions
                run: mvn -f ${{ inputs.app_directory }}/../pom.xml versions:commit
            -   name: Build with Maven
                run: mvn --batch-mode --update-snapshots install -DskipTests -f ${{ inputs.app_directory }}/../pom.xml
            -   name: Build and push docker
                run: |
                    mvn --batch-mode compile com.google.cloud.tools:jib-maven-plugin:3.1.4:build \
                    -f ${{ inputs.app_directory }}/pom.xml \
                    -Dimage=${{ secrets.acr_registry }}/${{ inputs.app_name }}:${{ inputs.ref_name }} \
                    -Djib.from.image=eclipse-temurin:${{ inputs.java_version }} \
                    -Djib.to.auth.username=${{ secrets.acr_username }} \
                    -Djib.to.auth.password=${{ secrets.acr_password }} \
                    -Djib.container.volumes=${{ inputs.jib_container_volumes }} \
                    -Djib.container.jvmFlags=-XX:MinRAMPercentage=60.0,-XX:MaxRAMPercentage=80.0

