name: Upload To Azure Blob Storage
on:
  workflow_call:
    inputs:
      artifact_to_upload:
        required: true
        type: string
        description: name of the artifact to upload
      container_name:
        required: false
        default: $web
        type: string
        description: name of the container name. default is '$web'

    secrets:
      blob_connection_string:
        required: true
        description: connection string to the azure blob

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: ${{ inputs.artifact_to_upload }}
          path: upload

      - uses: bacongobbler/azure-blob-storage-upload@50f7d898b7697e864130ea04c303ca38b5751c50 # v3.0.0
        with:
          source_dir: upload
          container_name: ${{ inputs.container_name }}
          connection_string: ${{ secrets.blob_connection_string }}
          overwrite: 'true'