name: Upload To Azure Blob Storage
on:
  workflow_call:
    inputs:
      artifact_to_upload:
        required: true
        type: string
        description: name of the artifact to upload
      container_name:
        required: false
        default: $web
        type: string
        description: name of the container name. default is '$web'
      
    secrets:
      blob_connection_string:
        required: true
        description: connection string to the azure blob

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact_to_upload }}
          path: upload
      
      - uses: bacongobbler/azure-blob-storage-upload@67563b802095fca59502cb0c240fdd6d6abf3d69 
        with:
          source_dir: upload
          container_name: ${{ inputs.container_name }}
          connection_string: ${{ secrets.blob_connection_string }}
          overwrite: 'true'