name: Runs Maven Install and releases to GitHub
on:
    workflow_call:
        inputs:
            ref_name:
                required: false
                default: ''
                type: string
                description: tag or branch name, used for mvn versions:set
            checkout_lfs:
                required: false
                default: false
                type: boolean
                description: Checkout with lfs, default false
            release_option_prerelease:
                type: boolean
                default: false
            release_option_files:
                type: string
                description: files for the artifact, e.g. 'eth-ws/target/eth-ws.war'
            changelog_file:
                type: string
                required: false
                description: Path to changelog file in format parsable by https://github.com/taiki-e/parse-changelog

        secrets:
            repo_token:
                required: true

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
                with:
                    ref: ${{ inputs.ref_name }}
                    lfs: ${{ inputs.checkout_lfs }}

            -   uses: taiki-e/install-action@3b0d937160738a7a458c7b13f8b05f08f3f72d80
                with:
                    tool: parse-changelog@0.6.8

            -   name: Strip leading `v` from VERSION
                id: strip_leading_v
                run: echo "TAG_NAME=${TAG_NAME##v}" >> $GITHUB_OUTPUT
                env:
                    TAG_NAME: ${{ inputs.ref_name }}

            -   name: Extract the release notes from the CHANGELOG.md file (skip for prerelease) (Release Body Option A)
                if: ${{ ! contains(inputs.ref_name, '-') && inputs.changelog_file }}
                run: echo "RELEASE_BODY=$(parse-changelog ${{ inputs.changelog_file }} $REF_NAME)" >> $GITHUB_ENV

            -   name: Set the release body for release (Release Body Option B)
                if: ${{ ! contains(inputs.ref_name, '-') && ! inputs.changelog_file }}
                run: echo "RELEASE_BODY=Release" >> $GITHUB_ENV

            -   name: Set the release body for prerelease (Release Body Option C)
                if: ${{ contains(inputs.ref_name, '-') }}
                id: set_release_body
                run: echo "RELEASE_BODY=Prerelease" >> $GITHUB_ENV

            -   name: Create new release
                uses: softprops/action-gh-release@69320dbe05506a9a39fc8ae11030b214ec2d1f87
                with:
                    tag_name: ${{ env.TAG_NAME }}
                    body: ${{ env.RELEASE_BODY }}
                    token: ${{ secrets.repo_token }}
                    prerelease: ${{ inputs.release_option_prerelease }}
                    files: ${{ inputs.release_option_files }}
