name: Run Api Tests
on:
    workflow_call:
        inputs:
            environment_to_test:
                required: true
                type: string
                description: environment to run tests against
            test_directory:
                required: true
                type: string
                description: directory containing env.json file and *.http files
            checkout_lfs:
                required: false
                default: false
                type: boolean
            checkout_submodules:
                required: false
                default: false
                type: string
                description: "Whether to checkout submodules: `true` to checkout submodules or `recursive` to recursively checkout submodules."

jobs:
    api-tests:
        runs-on: ubuntu-latest
        container:
            image: jetbrains/intellij-http-client:latest
        steps:
            -   uses: actions/checkout@v5
                with:
                    lfs: ${{ inputs.checkout_lfs }}
                    submodules: ${{ inputs.checkout_submodules }}

            -   name: Run Api Tests
                run: java -cp "/intellij-http-client/*" com.intellij.httpClient.cli.HttpClientMain -e ${{ inputs.environment_to_test}} -v ${{ inputs.test_directory}}/http-client.env.json --report ${{ inputs.test_directory}}/*.http
    
